config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :events
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "/admin" do
    resources :users
  end

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_sessions
  end

  root 'pages#home'

  get 'pages/about'

  get 'pages/books'

  resources :event_users, only: [:create, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
  # belongs_to :user

  has_many :event_users, :foreign_key => :attended_event_id
  has_many :attendees, :through => :event_users

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :pricing, :date, :schedule, :start_time, :pax_slots, :user_id, :location)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.event_users.build(attended_event_id: @event_id)) do |f| %>
	<div><%= f.hidden_field :attended_event_id, :value => @event_id %></div>
	<%= f.submit "Attend", class: "btn btn-large btn primary" %>
<%end%>

app/views/events/_attend_form.html.erb
<div id="attend_form">
	<% if current_user.attending?(@event) %> 
	  <%= render 'cancel' %>
	<% else %>
	  <%= render 'attend' %>
	<% end %>
</div>

app/views/events/_cancel.html.erb
<%= form_for(current_user.event_user.find_by(attended_event_id: @event_id), html: { method: :delete}) do |f|%>
	<% f.submit "Cancel", class: "btn btn-large" %>
<%end%>

app/views/events/_event_box.html.erb
<% @events.each do |event| %>	
	<ul class="style list-unstyled">
		<li>
		  <img class="img-circle pull-left" src="http://placehold.it/250x250" alt="">
				<a href="<%= event_path(event.id)%>">
		      <h3><%= event.name.capitalize %></h3>
		    </a>
		      <h4><%= event.location %></h4>
		      <p class="description"><%= event.description %></p>
		        <ul class="list-unstyled">
							<li>	
								<i class="ion-android-time"></i><span><%= "#{(event.date)} at #{(event.start_time.strftime("%I:%M %p"))}"%> </span>
							</li>
						</ul>
		      <a class="btn btn-primary" href="#">More Details <span class="ion-ios-arrow-forward"></span></a>

 					<% if can? :edit, event %>
            <%= link_to 'Edit', edit_event_path(event), class: "btn btn-warning" %>
            <%end%>

		      <% if can? :destroy, event %>
		      <%= link_to 'Destroy', event, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
		      	<%end%>
		     <%end%>
		</li>
	</ul>
<hr>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :pricing %><br>
    <%= f.text_field :pricing, :value => number_to_currency(f.object.pricing) %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
   <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :pax_slots %><br>
    <%= f.number_field :pax_slots %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="j">
  <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 centered">
          </div>
        </div><!--/row-->
      </div><!--/container-->
    </div><!-- /H -->
</div>

<div class="container">
  <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Upcoming Events
                <small></small>
            </h1>
        </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= render 'events/event_box' %>
      </div>
    </div>
     
</div>



<% if can? :create, Event %>
  <%= link_to 'New Event', new_event_path %>
<%end%>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @event.name %></h1>


<% if signed_in? %>
<div class="text-center"><%= render 'attend_form' %></div>
<% end %>

<p><b>Location: </b><%= @event.location %></p> 

<p><%= @event.description %></p>

</br>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>